### ISSUE TITLE
libdevice-cdio-perl: FTBFS against libcdio-dev 0.92

### ISSUE THREAD

**Issue by gregoa** [rocky/Perl-Device-Cdio#1]
We have the following bug reported to the Debian package of
Device-Cdio (https://bugs.debian.org/879891):

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Source: libdevice-cdio-perl
Version: 0.3.0-6
Severity: important
Tags: upstream sid buster
Justification: fails to build from source (but built successfully in the past)

As first noted on Ubuntu (thanks to doko), libdevice-cdio-perl fails
to build with newer versions of libcdio-dev, as 0.92-2 in
Debian/experimantal:

Ubuntu: https://launchpadlibrarian.net/343077055/buildlog_ubuntu-bionic-amd64.libdevice-cdio-perl_0.3.0-6build2_BUILDING.txt.gz

Debian/experimental:

dh_auto_build
	perl Build
Building Device-Cdio
Copying lib/Device/Cdio.pm -> blib/lib/Device/Cdio.pm
Copying lib/Device/Cdio/Device.pm -> blib/lib/Device/Cdio/Device.pm
Copying lib/Device/Cdio/ISO9660.pm -> blib/lib/Device/Cdio/ISO9660.pm
Copying lib/Device/Cdio/ISO9660/FS.pm -> blib/lib/Device/Cdio/ISO9660/FS.pm
Copying lib/Device/Cdio/ISO9660/IFS.pm -> blib/lib/Device/Cdio/ISO9660/IFS.pm
Copying lib/Device/Cdio/Track.pm -> blib/lib/Device/Cdio/Track.pm
Copying lib/Device/Cdio/Util.pm -> blib/lib/Device/Cdio/Util.pm
process swig files
swig: swig/perliso9660.swg -> perliso9660_wrap.c
swig -o perliso9660_wrap.c -perl -outdir lib swig/perliso9660.swg
Copying lib/perliso9660.pm -> blib/lib/perliso9660.pm
swig: swig/perlmmc.swg -> perlmmc_wrap.c
swig -o perlmmc_wrap.c -perl -outdir lib swig/perlmmc.swg
Copying lib/perlmmc.pm -> blib/lib/perlmmc.pm
swig: swig/perlcdio.swg -> perlcdio_wrap.c
swig -o perlcdio_wrap.c -perl -outdir lib swig/perlcdio.swg
Copying lib/perlcdio.pm -> blib/lib/perlcdio.pm
process c files
  CBuilder: 0.280225
(CC) ./perlcdio_wrap.c -> perlcdio.so
x86_64-linux-gnu-gcc -I/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -fPIC -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wno-strict-aliasing -Wno-unused-function -Wno-unused-value -Wno-unused-function -Wno-unused-variable -c -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g -O2 -fdebug-prefix-map=/build/libdevice-cdio-perl-0.3.0=. -fstack-protector-strong -Wformat -Werror=format-security -g -O2 -fdebug-prefix-map=/build/libdevice-cdio-perl-0.3.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -o ./perlcdio_wrap.o ./perlcdio_wrap.c
In file included from /usr/lib/x86_64-linux-gnu/perl/5.26/CORE/perl.h:5644:0,
                 from ./perlcdio_wrap.c:739:
./perlcdio_wrap.c: In function 'audio_get_status':
./perlcdio_wrap.c:1815:21: warning: implicit declaration of function 'cdio_from_bcd8'; did you mean 'cdio_open_bsdi'? [-Wimplicit-function-declaration]
             newSVuv(cdio_from_bcd8(sub.abs_addr.m)), 0);
                     ^
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE/embed.h:228:77: note: in definition of macro 'hv_common_key_len'
 #define hv_common_key_len(a,b,c,d,e,f) Perl_hv_common_key_len(aTHX_ a,b,c,d,e,f)
                                                                             ^
./perlcdio_wrap.c:1814:5: note: in expansion of macro 'hv_store'
     hv_store(audio_st, "abs_m", 5,
     ^~~~~~~~
./perlcdio_wrap.c:1815:13: note: in expansion of macro 'newSVuv'
             newSVuv(cdio_from_bcd8(sub.abs_addr.m)), 0);
             ^~~~~~~
./perlcdio_wrap.c: In function 'have_driver':
./perlcdio_wrap.c:2235:3: warning: 'CDIO_MIN_DRIVER' is deprecated: please use cdio_drivers [-Wdeprecated-declarations]
   if (driver_id < CDIO_MIN_DRIVER || driver_id > CDIO_MAX_DRIVER)
   ^~
In file included from /usr/include/cdio/cdio.h:35:0,
                 from ./perlcdio_wrap.c:1552:
/usr/include/cdio/device.h:202:1: note: declared here
 LIBCDIO_DEPRECATED(static const driver_id_t CDIO_MIN_DRIVER, "please use cdio_drivers") = DRIVER_AIX;
 ^
./perlcdio_wrap.c:2235:3: warning: 'CDIO_MAX_DRIVER' is deprecated: please use cdio_drivers [-Wdeprecated-declarations]
   if (driver_id < CDIO_MIN_DRIVER || driver_id > CDIO_MAX_DRIVER)
   ^~
In file included from /usr/include/cdio/cdio.h:35:0,
                 from ./perlcdio_wrap.c:1552:
/usr/include/cdio/device.h:204:1: note: declared here
 LIBCDIO_DEPRECATED(static const driver_id_t CDIO_MAX_DRIVER, "please use cdio_drivers") = DRIVER_NRG;
 ^
./perlcdio_wrap.c: In function 'get_cdtext':
./perlcdio_wrap.c:2296:24: error: too many arguments to function 'cdio_get_cdtext'
     cdtext = ( char **)cdio_get_cdtext (p_cdio, (track_t) track);
                        ^~~~~~~~~~~~~~~
In file included from /usr/include/cdio/cdio.h:61:0,
                 from ./perlcdio_wrap.c:1552:
/usr/include/cdio/disc.h:77:13: note: declared here
   cdtext_t *cdio_get_cdtext (CdIo_t *p_cdio);
             ^~~~~~~~~~~~~~~
./perlcdio_wrap.c: In function '_wrap_get_tray_status':
./perlcdio_wrap.c:4846:19: warning: implicit declaration of function 'mmc_get_tray_status'; did you mean '_wrap_get_tray_status'? [-Wimplicit-function-declaration]
     result = (int)mmc_get_tray_status((CdIo_t const *)arg1);
                   ^~~~~~~~~~~~~~~~~~~
                   _wrap_get_tray_status
./perlcdio_wrap.c: In function 'boot_perlcdio':
./perlcdio_wrap.c:6200:5: warning: 'CDIO_MIN_DRIVER' is deprecated: please use cdio_drivers [-Wdeprecated-declarations]
     sv_setsv(sv, SWIG_From_long  SWIG_PERL_CALL_ARGS_1((long)(CDIO_MIN_DRIVER)));
     ^~~~~~~~
In file included from /usr/include/cdio/cdio.h:35:0,
                 from ./perlcdio_wrap.c:1552:
/usr/include/cdio/device.h:202:1: note: declared here
 LIBCDIO_DEPRECATED(static const driver_id_t CDIO_MIN_DRIVER, "please use cdio_drivers") = DRIVER_AIX;
 ^
./perlcdio_wrap.c:6205:5: warning: 'CDIO_MIN_DEVICE_DRIVER' is deprecated: please use cdio_device_drivers [-Wdeprecated-declarations]
     sv_setsv(sv, SWIG_From_long  SWIG_PERL_CALL_ARGS_1((long)(CDIO_MIN_DEVICE_DRIVER)));
     ^~~~~~~~
In file included from /usr/include/cdio/cdio.h:35:0,
                 from ./perlcdio_wrap.c:1552:
/usr/include/cdio/device.h:203:1: note: declared here
 LIBCDIO_DEPRECATED(static const driver_id_t CDIO_MIN_DEVICE_DRIVER, "please use cdio_device_drivers") = DRIVER_AIX;
 ^
./perlcdio_wrap.c:6210:5: warning: 'CDIO_MAX_DRIVER' is deprecated: please use cdio_drivers [-Wdeprecated-declarations]
     sv_setsv(sv, SWIG_From_long  SWIG_PERL_CALL_ARGS_1((long)(CDIO_MAX_DRIVER)));
     ^~~~~~~~
In file included from /usr/include/cdio/cdio.h:35:0,
                 from ./perlcdio_wrap.c:1552:
/usr/include/cdio/device.h:204:1: note: declared here
 LIBCDIO_DEPRECATED(static const driver_id_t CDIO_MAX_DRIVER, "please use cdio_drivers") = DRIVER_NRG;
 ^
./perlcdio_wrap.c:6215:5: warning: 'CDIO_MAX_DEVICE_DRIVER' is deprecated: please use cdio_device_drivers [-Wdeprecated-declarations]
     sv_setsv(sv, SWIG_From_long  SWIG_PERL_CALL_ARGS_1((long)(CDIO_MAX_DEVICE_DRIVER)));
     ^~~~~~~~
In file included from /usr/include/cdio/cdio.h:35:0,
                 from ./perlcdio_wrap.c:1552:
/usr/include/cdio/device.h:205:1: note: declared here
 LIBCDIO_DEPRECATED(static const driver_id_t CDIO_MAX_DEVICE_DRIVER, "please use cdio_device_drivers") = DRIVER_WIN32;
 ^
error building ./perlcdio_wrap.o from './perlcdio_wrap.c' at /usr/share/perl/5.26/ExtUtils/CBuilder/Base.pm line 174.
dh_auto_build: perl Build returned exit code 2
debian/rules:22: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2



```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by rocky** [comment]
Will look at. Thanks for passing on. 

(BTW, I have a number of _other_ cool Perl packages, the most unique one is the debugger:  https://metacpan.org/pod/Devel::Trepan )

**Comment by adconrad** [comment]
The real issue here seems to just be that you haven't tagged an upstream release in eons, and Debian/Ubuntu are still shipping your 0.3.0 that you tagged in 2011.  I rolled up a snapshot release as of your latest commit, and it seems to do the trick:

https://launchpad.net/ubuntu/+source/libdevice-cdio-perl/0.3.0+git20140524-0ubuntu1

It would be lovely if you'd test and tag a new release occasionally, as downstream distributors tend to do things like poll the github project/releases page to see if there's a new "stable" release they should be pulling in.  The lack thereof here has embarrassingly led to Debian derivatives losing out on several years' worth of your commits.

**Comment by adconrad** [comment]
@gregoa I can NMU the above to Debian, if you like, or you can check over my work and do your own upload.  If you do the latter, please use the same orig.tar.gz from that build (linked on that launchpad page), so we can easily sync your upload over mine.

**Comment by rocky** [comment]
@adconrad Thanks for fixing.  I'm having a hard time understanding the jargon. 

Here is what I understand. Debian hasn't been tracking newer versions of libcdio. I believe it is on version 0.83 while 0.94 is the most recent release (and I should come out with 0.95 in the near future). 

From your patches I see that I should bump min version in Device::Cdio and post that to CPAN. But I see there are other changes. Most reliable and easiest for me would be for you to put in a pull request for the changes though, and then I'll run that through the various tests. 

What does NMU stand for?

**Comment by gregoa** [comment]
On Sun, 29 Oct 2017 09:29:32 +0000, Adam Conrad wrote:

> @gregoa I can NMU the above to Debian, if you like, or you can
> check over my work and do your own upload. If you do the latter,
> please use the same orig.tar.gz from that build (linked on that
> launchpad page), so we can easily sync your upload over mine.

Thanks for the updates and your work, @adconrad.

TBH, I'd prefer to wait for a new upstream release on the CPAN for a
couple of days. Otherwise I'm happy to take the Ubuntu tarball and
merge it into our packaging repo, which has accumulated some other
(packaging related) changes since the last upload.
 

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at/ - Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Tony Joe White: Selena

**Comment by adconrad** [comment]
@rocky Debian is absolutely tracking new versions of libcdio.  Currently we're working on moving to 0.94, which is how we ran into this issue.  What we haven't been tracking is new versions of libdevice-cdio-perl, apparently, and I suspect that has to do with the last tagged version being 0.3.0.

As for the talk of NMUs (non-maintainer upload) and such, that was aimed at the Debian maintainer who filed this issue, asking if he wanted me to upload my above Ubuntu upload to Debian as well.

It would absolutely be preferable if you cut a new release of the module for @gregoa to package and upload to Debian, though.

**Comment by rocky** [comment]
@adconrad thanks for the information and clarification. I just tried the Device::Cdio code on the current libcdio git sources and it still passes all of the tests. 

So is it just a matter of doing the steps to make a release and then pushing this version, 0.3.1, to CPAN?

**Comment by adconrad** [comment]
@rocky Yup, your current git head is the snapshot I packaged up for Ubuntu (and pointed to above) and, indeed, it passes all the tests.  So, that should do.

**Comment by rocky** [comment]
Ok. Thanks again for the clarification.

There will be release 0.3.1 soon. 
 
(I need first though to test on all versions of Perl I have, and to the usual release dance which I'll probably need to updated as things have gotten more rigorous over the years.)

**Comment by gregoa** [comment]
On Sun, 29 Oct 2017 09:10:16 -0700, R. Bernstein wrote:

> From your patches I see that I should bump min version in
> Device::Cdio and post that to CPAN. But I see there are other
> changes. Most reliable and easiest for me would be for you to put
> in a pull request for the changes though, and then I'll run that
> through the various tests.

From what I see, @adconrad's libdevice-cdio-perl_0.3.0+git20140524.orig.tar.gz
is just the contents of your git repo; at least I get the very same
when running git-archive against HEAD in the repo.
 
So yes, just a "normal" release of the distribution on the CPAN would
be easiest for us.


Cheers,
gregor

**Comment by rocky** [comment]
Release 0.3.1 is now on [CPAN](https://metacpan.org/source/ROCKY/Device-Cdio-v0.3.1), [ftp.gnu.org](https://ftp.gnu.org/pub/gnu/libcdio/), and is [tagged in git](https://github.com/rocky/Perl-Device-Cdio/tree/release-0.3.1). 

Even though I added Travis CI testing, in a day I guess CPAN Testers will kick in. Changes over what adconrad had were of an administrivia and packaging nature, such as CI testing.

Mild rebuke: One reason this code has been so back-level is that the rating for it is pretty low. I use ratings to help me decide what to work on when there is a choice. I notice that neither of you have upvoted this or the CPAN distribution. 

I greatly appreciate what "downsteam" packagers do. But one thing that sucks about the interaction is it usually of the complaint kind. I have no idea of your existence or whether something is being packaged for a distro,  what the release schedules are for distros _except_ when there is a problem.  

(On the flip side, there is something I should be doing to track what's going on with this in Debian and Ubuntu, lemme know.)

**Comment by gregoa** [comment]
On Sun, 29 Oct 2017 23:52:45 +0000, R. Bernstein wrote:

> Release 0.3.1 is now on
> [CPAN](https://metacpan.org/source/ROCKY/Device-Cdio-v0.3.1),
> [ftp.gnu.org](ftp://ftp.gnu.org/pub/gnu/libcdio/), and is [tagged
> in git](https://github.com/rocky/Perl-Device-Cdio/tree/release-0.3.1).

Thank you!

And uploaded to Debian/experimental.
(Experimental instead of unstable because of the newer libcdio.
And it took me a bit to realise that we need a newer libiso9660-dev
as well :))

And (finally!) 2 new pull requests/issues filed for the last 2
remaining patches.
 
> Mild rebuke: One reason this code has been so back-level is that
> the rating for it is pretty low. I use ratings to help me decide
> what to work on when there is a choice. I notice that neither of
> you have upvoted this or the CPAN distribution.

True but the reason is quite simple: The Debian Perl Group
(consisting of ~100 members) jointly maintains something like 3500
CPAN distributions. And obviously not all of us personally use each
and every package; besides that a "mass upvoting" feels wrong as well
:)
 
> I greatly appreciate what "downsteam" packagers do. But one thing
> that sucks about the interaction is it usually of the complaint
> kind. I have no idea of your existence or whether something is
> being packaged for a distro _except_ when there is a problem.

Yeah, I see your point.
 
> (On the flip side, there is something I should be doing to track
> what's going on with this in Debian and Ubuntu, lemme know.)

For Debian packages of your perl distributions, you could "subscribe"
to them on tracker, e.g. https://tracker.debian.org/libdevice-cdio-perl
then you get mails about bug reports, new uploads etc.
 
I think Ubuntu/Launchpad provides a similar service.


Thanks again for your work!


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at/ - Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: The Who: Let's See Action

**Comment by gregoa** [comment]
Oh, and we can close this issue as well as per the 0.3.1 release.
Thanks again.

**Comment by rocky** [comment]
When the dust settles, there may be a 0.3.2 release. Hopefully that will hold us for another 5 years.

**Comment by rocky** [comment]
And I've subscribed to the Debian tracker now.

**Comment by rocky** [comment]
Another release was just cut to CPAN and ftp.gnu.org. This represents basically a 6-year cleanup from the 2011 release. With luck, it will hold another 6 years.

**Comment by gregoa** [comment]
On Thu, 02 Nov 2017 02:27:58 +0000, R. Bernstein wrote:

> Another release was just cut to CPAN and ftp.gnu.org. This
> represents basically a 6-year cleanup from the 2011 release. With
> luck, it will hold another 6 years.

Thanks!
Uploaded to Debian/experimental.


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at/ - Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: John Zorn & Masada: Tohorot
