### ISSUE TITLE
spelling mistakes

### ISSUE THREAD

**Issue by gregoa** [rocky/Perl-Device-Cdio#4]
In Debian we are currently applying the following patch to
Device-Cdio.
We thought you might be interested in it too.

    Description: spelling mistake
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2017-10-30
    Bug: 
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdevice-cdio-perl.git/plain/debian/patches/06_spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by gregoa** [comment]
(Should have been a pull request, for some unknown reason our tool for creating PRs from patches failed in this case.)

**Comment by rocky** [comment]
Applied in commit bc9fc96b201b7f8d7f7728a0068e8a4f6a3cec09  with adding CircleCI testing and there was one more slight grammar correction. Please double check and close if this is sufficient.

**Comment by gregoa** [comment]
Looks good, thanks alot!
